class HadethTitleModel {
  final String title;
  HadethTitleModel({required this.title});

  static List<HadethTitleModel> hadeethNumberList = [
    HadethTitleModel(title: "الحد يث الأول"),
    HadethTitleModel(title: "الحد يث الثاني"),
    HadethTitleModel(title: "الحد يث الـثـالـث"),
    HadethTitleModel(title: "الحد يث الـرابع"),
    HadethTitleModel(title: "الحد يث الخامس"),
    HadethTitleModel(title: "الحد يث السادس"),
    HadethTitleModel(title: "الحد يث السابع"),
    HadethTitleModel(title: "الحد يث الثامن"),
    HadethTitleModel(title: "الحديث التاسع"),
    HadethTitleModel(title: "الحديث العاشر"),
    HadethTitleModel(title: "الحديث الحادي عشر"),
    HadethTitleModel(title: "الحد يث الثاني عشر"),
    HadethTitleModel(title: "الحد يث الثالث عشر"),
    HadethTitleModel(title: "الحد يث الرابع عشر"),
    HadethTitleModel(title: "الحد يث الخامس عشر"),
    HadethTitleModel(title: "الحديث السادس عشر"),
    HadethTitleModel(title: "الحديث السابع عشر"),
    HadethTitleModel(title: "الحديث الثامن عشر"),
    HadethTitleModel(title: "الحد يث التاسع عشر"),
    HadethTitleModel(title: "الحد يث العشرون"),
    HadethTitleModel(title: "الحد يث الحادي والعشرون"),
    HadethTitleModel(title: "الحد يث الثاني والعشرون"),
    HadethTitleModel(title: "الحديث الثالث والعشرون"),
    HadethTitleModel(title: "الـحديث الرابع والعشرون"),
    HadethTitleModel(title: "الحديث الخامس والعشرون"),
    HadethTitleModel(title: "الحد يث السادس والعشرون"),
    HadethTitleModel(title: "الحد يث السابع والعشرون"),
    HadethTitleModel(title: "الحد يث الثامن والعشرون"),
    HadethTitleModel(title: "الحد يث التاسع والعشرون"),
    HadethTitleModel(title: "الحديث الثلا ثــون"),
    HadethTitleModel(title: "الـحديث الحادي والثلاثون"),
    HadethTitleModel(title: "الحديث الثاني والثلاثون"),
    HadethTitleModel(title: "الحد يث الثالث والثلاثون"),
    HadethTitleModel(title: "الحد يث الرابع والثلاثون"),
    HadethTitleModel(title: "الحد يث الخامس والثلاثون"),
    HadethTitleModel(title: "الحد يث السادس والثلاثون"),
    HadethTitleModel(title: "الحديث السابع والثلاثون"),
    HadethTitleModel(title: "الـحديث الثامن والثلاثون"),
    HadethTitleModel(title: "الحديث التاسع والثلاثون"),
    HadethTitleModel(title: "الحد يث الأربعون"),
    HadethTitleModel(title: "الحد يث الحادي والأربعون"),
    HadethTitleModel(title: "الحد يث الثاني والأربعـون"),
    HadethTitleModel(title: "الحد يث الثالث والأربعون"),
    HadethTitleModel(title: "الحديث الرابع والأربعون"),
    HadethTitleModel(title: "الـحديث الخامس والأربعون"),
    HadethTitleModel(title: "الحديث السادس والأربعون"),
    HadethTitleModel(title: "الحديث السابع والأربعون"),
    HadethTitleModel(title: "الـحديث الثامن والأربعون"),
    HadethTitleModel(title: "الحديث التاسع والأربعون"),
    HadethTitleModel(title: "الحديث الخمسون"),
  ];
}
